export enum WebSocketEvent {
  RECEIVE_NEW_NOTIFICATION = 'RECEIVE_NEW_NOTIFICATION',
  EDIT_MESSAGE = 'EDIT_MESSAGE',
  REMOVE_MESSAGE = 'REMOVE_MESSAGE',
  PIN_MESSAGE = 'PIN_MESSAGE',
  MARK_AS_READ = 'MARK_AS_READ',
  RECEIVE_NEW_MESSAGE = 'RECEIVE_NEW_MESSAGE',
  BLOCK_USER = 'BLOCK_USER',
}
